import time
from collections import deque
from find_patient import find_patient
from get_text import getText
from macros.auto_macros import autoFluraNorma, autoOGKNorma
from macros.backbone_macros import shop, pop, shopGop
from macros.cranium_macros import craniumNorma
from macros.create_refferal_macros import create_referal
from macros.double_separeted_macros import ogkObpSeparatedCT, fluraObpSeparatedCT, craniumOgkSeparatedCT
from macros.obp_macros import OBPNorma, urografiaNorma
from write_text import writeText, writePass, writeKey
from macros.double_macros import craniumLungsMacros, OgkObpNorma
from macros.lungs_macros import fluraNormaShort, fluraNorma, rOGK, rOGKPrint, fluraNormaCT, OGKNormaCT
from find_button import FindButton as FB
from macros.macros import startIK, restartIK, endIK, keyMacros
from macros.ppn_macros import ppnSinusitRight, ppnNorma, ppnSinusitLeft
from omc_control import getScreenTemplate, waitChanges
from keyboard import keyboardTap, KeyboardPackagesUdp as KP
from mouse import mouseTap, MousePackagesUdp as MP, initialMousePosition, mousePosition, mouseDoubleLKMTap
from keyboard import keyboardLongTap
from find_title import FindTitles as FT
from openpyxl import load_workbook
import arrow

FIOList = deque([



])
my_iter = iter(FIOList)

i = 0
PatientDict = {}


def autoFluraNormaRefferal():  # Автоматическая флюорография с созданием направления
    while True:
        try:
            FIO = next(my_iter)
            print(FIO)
            FB.findSearchMainButton()  # находим поле поиска
            mouseTap(MP.LKM_MOUSE)
            keyboardLongTap(KP.LeftControl)  # выделение текста
            keyboardTap(KP.A)
            getScreenTemplate()
            writeText(FIO)  # Пишем полученные данные на другом компе
            waitChanges()
            time.sleep(3)
            create_referal()  # cоздаем направление
            fluraNormaShort()
            time.sleep(3)
        except StopIteration:
            break


def auto_fluro_ct():  # Автоматическая флюорография для пациентов с стационара
    while True:
        try:
            FIO = next(my_iter)
            print(FIO)
            FB.findSearchMainButton()  # находим поле поиска
            mouseTap(MP.LKM_MOUSE)
            keyboardLongTap(KP.LeftControl)
            keyboardTap(KP.A)
            time.sleep(0.5)
            writeText(FIO)  # Пишем полученные данные на другом компе
            time.sleep(3)
            fluraNormaCT()
            time.sleep(3)
        except StopIteration:
            break


def autoOGKCT():
    while True:
        try:
            FIO = next(my_iter)
            print(FIO)
            FB.findSearchMainButton()  # находим поле поиска
            mouseTap(MP.LKM_MOUSE)
            keyboardLongTap(KP.LeftControl)
            keyboardTap(KP.A)
            time.sleep(0.5)
            writeText(FIO)  # Пишем полученные данные на другом компе
            time.sleep(3)
            OGKNormaCT()
            time.sleep(3)
        except StopIteration:
            break


def autoFluraFromDict():  # Автоматическая полная флюорография, получаемую из списка
    fioList = list(PatientDict.keys())
    dateList = list(PatientDict.values())
    while i < len(fioList):
        keyboardTap(KP.F10)
        fio = fioList.pop(0)
        print(fio)
        FB.find(FB.familyField)
        writeText(fio)
        birth = dateList.pop(0)
        FB.find(FB.birthField)
        mouseTap(MP.LKM_MOUSE)
        writeText(birth)
        print(birth)
        FB.find(FB.prodolgitButton)
        mouseTap(MP.LKM_MOUSE)
        fluraNorma()
        time.sleep(3)



#autoOGKCT()
#auto_fluro_ct()
# autoFluraFromDict()
#OBPNorma()
# findPatientWithBirth()
# fluraObpSeparetedCT()
#craniumOgkSeparatedCT()
#ogkObpSeparatedCT()
# autoFluraFromList()
# fluraNormaShort()
# autoFluraNormaRefferal()
#urografiaNorma()
# autoFluraCT()
# ppnSinusitRight()
# kneesJoints()
# ppnNorma()
# pop()
# shop()
# autoFluraNorma()
# endIK()
# restartIK()
# autoOGKNorma()
# autoFluraNormaShort()
# writePass()
# getText()
# time.sleep(3)
# fluraNorma()
# rOGK()
# antiSleep()
# pop()
# findPatient()


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 800)
        font = QtGui.QFont()
        font.setPointSize(13)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.family = QtWidgets.QLabel(self.centralwidget)
        self.family.setGeometry(QtCore.QRect(0, 40, 260, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.family.setFont(font)
        self.family.setTextFormat(QtCore.Qt.RichText)
        self.family.setObjectName("family")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(270, 40, 260, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.name.setFont(font)
        self.name.setTextFormat(QtCore.Qt.RichText)
        self.name.setObjectName("name")
        self.middle_name = QtWidgets.QLabel(self.centralwidget)
        self.middle_name.setGeometry(QtCore.QRect(550, 40, 260, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.middle_name.setFont(font)
        self.middle_name.setTextFormat(QtCore.Qt.RichText)
        self.middle_name.setObjectName("middle_name")
        self.birth_date = QtWidgets.QLabel(self.centralwidget)
        self.birth_date.setGeometry(QtCore.QRect(830, 40, 260, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.birth_date.setFont(font)
        self.birth_date.setTextFormat(QtCore.Qt.RichText)
        self.birth_date.setObjectName("birth_date")
        self.main = QtWidgets.QTabWidget(self.centralwidget)
        self.main.setGeometry(QtCore.QRect(0, 160, 1121, 611))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.main.setFont(font)
        self.main.setObjectName("main")
        self.OGK_tab = QtWidgets.QWidget()
        self.OGK_tab.setObjectName("OGK_tab")
        self.pushButton_fluraNorma = QtWidgets.QPushButton(self.OGK_tab)
        self.pushButton_fluraNorma.setGeometry(QtCore.QRect(250, 20, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_fluraNorma.setFont(font)
        self.pushButton_fluraNorma.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_fluraNorma.setObjectName("pushButton_fluraNorma")
        self.pushButton_fluraNormaShort = QtWidgets.QPushButton(self.OGK_tab)
        self.pushButton_fluraNormaShort.setGeometry(QtCore.QRect(250, 90, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_fluraNormaShort.setFont(font)
        self.pushButton_fluraNormaShort.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_fluraNormaShort.setObjectName("pushButton_fluraNormaShort")
        self.pushButton_TBCExodus = QtWidgets.QPushButton(self.OGK_tab)
        self.pushButton_TBCExodus.setGeometry(QtCore.QRect(560, 89, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_TBCExodus.setFont(font)
        self.pushButton_TBCExodus.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_TBCExodus.setObjectName("pushButton_TBCExodus")
        self.pushButton_TBCExodusRight = QtWidgets.QPushButton(self.OGK_tab)
        self.pushButton_TBCExodusRight.setGeometry(QtCore.QRect(560, 160, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_TBCExodusRight.setFont(font)
        self.pushButton_TBCExodusRight.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_TBCExodusRight.setObjectName("pushButton_TBCExodusRight")
        self.pushButton_TBCExodusRight_2 = QtWidgets.QPushButton(self.OGK_tab)
        self.pushButton_TBCExodusRight_2.setGeometry(QtCore.QRect(560, 20, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_TBCExodusRight_2.setFont(font)
        self.pushButton_TBCExodusRight_2.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_TBCExodusRight_2.setObjectName("pushButton_TBCExodusRight_2")
        self.OGKButton_OGKprint = QtWidgets.QPushButton(self.OGK_tab)
        self.OGKButton_OGKprint.setGeometry(QtCore.QRect(0, 90, 221, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.OGKButton_OGKprint.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.OGKButton_OGKprint.setFont(font)
        self.OGKButton_OGKprint.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.OGKButton_OGKprint.setObjectName("OGKButton_OGKprint")
        self.OGKAutoButton = QtWidgets.QPushButton(self.OGK_tab)
        self.OGKAutoButton.setGeometry(QtCore.QRect(0, 160, 221, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.OGKAutoButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.OGKAutoButton.setFont(font)
        self.OGKAutoButton.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.OGKAutoButton.setObjectName("OGKAutoButton")
        self.pushButton_fluraNormaAvto = QtWidgets.QPushButton(self.OGK_tab)
        self.pushButton_fluraNormaAvto.setGeometry(QtCore.QRect(250, 160, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_fluraNormaAvto.setFont(font)
        self.pushButton_fluraNormaAvto.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_fluraNormaAvto.setObjectName("pushButton_fluraNormaAvto")
        self.OGKButtonCT = QtWidgets.QPushButton(self.OGK_tab)
        self.OGKButtonCT.setGeometry(QtCore.QRect(0, 230, 221, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.OGKButtonCT.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.OGKButtonCT.setFont(font)
        self.OGKButtonCT.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.OGKButtonCT.setObjectName("OGKButtonCT")
        self.pushButton_fluraNormaCT = QtWidgets.QPushButton(self.OGK_tab)
        self.pushButton_fluraNormaCT.setGeometry(QtCore.QRect(250, 230, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_fluraNormaCT.setFont(font)
        self.pushButton_fluraNormaCT.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_fluraNormaCT.setObjectName("pushButton_fluraNormaCT")
        self.pushButton_pneumonia_right = QtWidgets.QPushButton(self.OGK_tab)
        self.pushButton_pneumonia_right.setGeometry(QtCore.QRect(300, 400, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_pneumonia_right.setFont(font)
        self.pushButton_pneumonia_right.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_pneumonia_right.setObjectName("pushButton_pneumonia_right")
        self.pushButton_pneumonia_left = QtWidgets.QPushButton(self.OGK_tab)
        self.pushButton_pneumonia_left.setGeometry(QtCore.QRect(0, 400, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_pneumonia_left.setFont(font)
        self.pushButton_pneumonia_left.setAutoFillBackground(False)
        self.pushButton_pneumonia_left.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_pneumonia_left.setObjectName("pushButton_pneumonia_left")
        self.pushButton_pneumonia_right_left = QtWidgets.QPushButton(self.OGK_tab)
        self.pushButton_pneumonia_right_left.setGeometry(QtCore.QRect(600, 400, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_pneumonia_right_left.setFont(font)
        self.pushButton_pneumonia_right_left.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_pneumonia_right_left.setObjectName("pushButton_pneumonia_right_left")
        self.pushButton_OGK_norma = QtWidgets.QPushButton(self.OGK_tab)
        self.pushButton_OGK_norma.setGeometry(QtCore.QRect(0, 20, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_OGK_norma.setFont(font)
        self.pushButton_OGK_norma.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_OGK_norma.setObjectName("pushButton_OGK_norma")
        self.pushButton_plevrit_left = QtWidgets.QPushButton(self.OGK_tab)
        self.pushButton_plevrit_left.setGeometry(QtCore.QRect(0, 500, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_plevrit_left.setFont(font)
        self.pushButton_plevrit_left.setAutoFillBackground(False)
        self.pushButton_plevrit_left.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_plevrit_left.setObjectName("pushButton_plevrit_left")
        self.pushButton_plevrit_right = QtWidgets.QPushButton(self.OGK_tab)
        self.pushButton_plevrit_right.setGeometry(QtCore.QRect(300, 500, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_plevrit_right.setFont(font)
        self.pushButton_plevrit_right.setAutoFillBackground(False)
        self.pushButton_plevrit_right.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_plevrit_right.setObjectName("pushButton_plevrit_right")
        self.pushButton_fluraShortAuto = QtWidgets.QPushButton(self.OGK_tab)
        self.pushButton_fluraShortAuto.setGeometry(QtCore.QRect(250, 300, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_fluraShortAuto.setFont(font)
        self.pushButton_fluraShortAuto.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_fluraShortAuto.setObjectName("pushButton_fluraShortAuto")
        self.main.addTab(self.OGK_tab, "")
        self.backbone_tab = QtWidgets.QWidget()
        self.backbone_tab.setObjectName("backbone_tab")
        self.pushButton_shopOX = QtWidgets.QPushButton(self.backbone_tab)
        self.pushButton_shopOX.setGeometry(QtCore.QRect(10, 10, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_shopOX.setFont(font)
        self.pushButton_shopOX.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_shopOX.setObjectName("pushButton_shopOX")
        self.pushButton_gopOX = QtWidgets.QPushButton(self.backbone_tab)
        self.pushButton_gopOX.setGeometry(QtCore.QRect(250, 10, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_gopOX.setFont(font)
        self.pushButton_gopOX.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_gopOX.setObjectName("pushButton_gopOX")
        self.pushButton_popOX = QtWidgets.QPushButton(self.backbone_tab)
        self.pushButton_popOX.setGeometry(QtCore.QRect(490, 10, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_popOX.setFont(font)
        self.pushButton_popOX.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_popOX.setObjectName("pushButton_popOX")
        self.pushButton_shopGopOX = QtWidgets.QPushButton(self.backbone_tab)
        self.pushButton_shopGopOX.setGeometry(QtCore.QRect(10, 100, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_shopGopOX.setFont(font)
        self.pushButton_shopGopOX.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_shopGopOX.setObjectName("pushButton_shopGopOX")
        self.pushButton_GopPopOX = QtWidgets.QPushButton(self.backbone_tab)
        self.pushButton_GopPopOX.setGeometry(QtCore.QRect(320, 100, 261, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_GopPopOX.setFont(font)
        self.pushButton_GopPopOX.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_GopPopOX.setObjectName("pushButton_GopPopOX")
        self.main.addTab(self.backbone_tab, "")
        self.cranium_ppn_tab = QtWidgets.QWidget()
        self.cranium_ppn_tab.setObjectName("cranium_ppn_tab")
        self.pushButton_craniumNorma = QtWidgets.QPushButton(self.cranium_ppn_tab)
        self.pushButton_craniumNorma.setGeometry(QtCore.QRect(10, 10, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_craniumNorma.setFont(font)
        self.pushButton_craniumNorma.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_craniumNorma.setObjectName("pushButton_craniumNorma")
        self.pushButton_ppnNorma = QtWidgets.QPushButton(self.cranium_ppn_tab)
        self.pushButton_ppnNorma.setGeometry(QtCore.QRect(200, 10, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_ppnNorma.setFont(font)
        self.pushButton_ppnNorma.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_ppnNorma.setObjectName("pushButton_ppnNorma")
        self.pushButton_ppnSinusitRight = QtWidgets.QPushButton(self.cranium_ppn_tab)
        self.pushButton_ppnSinusitRight.setGeometry(QtCore.QRect(400, 10, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_ppnSinusitRight.setFont(font)
        self.pushButton_ppnSinusitRight.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_ppnSinusitRight.setObjectName("pushButton_ppnSinusitRight")
        self.pushButton_ppnSinusitLeft = QtWidgets.QPushButton(self.cranium_ppn_tab)
        self.pushButton_ppnSinusitLeft.setGeometry(QtCore.QRect(590, 10, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_ppnSinusitLeft.setFont(font)
        self.pushButton_ppnSinusitLeft.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_ppnSinusitLeft.setObjectName("pushButton_ppnSinusitLeft")
        self.pushButton_ppnSinusitRightLeft = QtWidgets.QPushButton(self.cranium_ppn_tab)
        self.pushButton_ppnSinusitRightLeft.setGeometry(QtCore.QRect(10, 100, 281, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_ppnSinusitRightLeft.setFont(font)
        self.pushButton_ppnSinusitRightLeft.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_ppnSinusitRightLeft.setObjectName("pushButton_ppnSinusitRightLeft")
        self.main.addTab(self.cranium_ppn_tab, "")
        self.double_shablon_tab = QtWidgets.QWidget()
        self.double_shablon_tab.setObjectName("double_shablon_tab")
        self.pushButton_cranium_lungs = QtWidgets.QPushButton(self.double_shablon_tab)
        self.pushButton_cranium_lungs.setGeometry(QtCore.QRect(10, 20, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_cranium_lungs.setFont(font)
        self.pushButton_cranium_lungs.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_cranium_lungs.setObjectName("pushButton_cranium_lungs")
        self.pushButton_lungs_belly = QtWidgets.QPushButton(self.double_shablon_tab)
        self.pushButton_lungs_belly.setGeometry(QtCore.QRect(230, 20, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_lungs_belly.setFont(font)
        self.pushButton_lungs_belly.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_lungs_belly.setObjectName("pushButton_lungs_belly")
        self.pushButton_ppnLungs = QtWidgets.QPushButton(self.double_shablon_tab)
        self.pushButton_ppnLungs.setGeometry(QtCore.QRect(450, 20, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_ppnLungs.setFont(font)
        self.pushButton_ppnLungs.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_ppnLungs.setObjectName("pushButton_ppnLungs")
        self.pushButton_pop_hips = QtWidgets.QPushButton(self.double_shablon_tab)
        self.pushButton_pop_hips.setGeometry(QtCore.QRect(10, 100, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_pop_hips.setFont(font)
        self.pushButton_pop_hips.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_pop_hips.setObjectName("pushButton_pop_hips")
        self.main.addTab(self.double_shablon_tab, "")
        self.trauma_tab = QtWidgets.QWidget()
        self.trauma_tab.setObjectName("trauma_tab")
        self.pushButton_perelom_tip_left = QtWidgets.QPushButton(self.trauma_tab)
        self.pushButton_perelom_tip_left.setGeometry(QtCore.QRect(20, 20, 421, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_perelom_tip_left.setFont(font)
        self.pushButton_perelom_tip_left.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_perelom_tip_left.setObjectName("pushButton_perelom_tip_left")
        self.pushButton_perelom_tip_right = QtWidgets.QPushButton(self.trauma_tab)
        self.pushButton_perelom_tip_right.setGeometry(QtCore.QRect(470, 20, 441, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_perelom_tip_right.setFont(font)
        self.pushButton_perelom_tip_right.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_perelom_tip_right.setObjectName("pushButton_perelom_tip_right")
        self.pushButton_BonesNorma = QtWidgets.QPushButton(self.trauma_tab)
        self.pushButton_BonesNorma.setGeometry(QtCore.QRect(20, 100, 391, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_BonesNorma.setFont(font)
        self.pushButton_BonesNorma.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_BonesNorma.setObjectName("pushButton_BonesNorma")
        self.main.addTab(self.trauma_tab, "")
        self.joint_tab = QtWidgets.QWidget()
        self.joint_tab.setObjectName("joint_tab")
        self.DOA = QtWidgets.QGroupBox(self.joint_tab)
        self.DOA.setGeometry(QtCore.QRect(0, 10, 211, 221))
        self.DOA.setObjectName("DOA")
        self.pushButton_DOAHips = QtWidgets.QPushButton(self.DOA)
        self.pushButton_DOAHips.setGeometry(QtCore.QRect(0, 180, 211, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_DOAHips.setFont(font)
        self.pushButton_DOAHips.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_DOAHips.setObjectName("pushButton_DOAHips")
        self.radioButton_rightHips = QtWidgets.QRadioButton(self.DOA)
        self.radioButton_rightHips.setGeometry(QtCore.QRect(20, 20, 91, 17))
        self.radioButton_rightHips.setObjectName("radioButton_rightHips")
        self.radioButton_leftHips = QtWidgets.QRadioButton(self.DOA)
        self.radioButton_leftHips.setGeometry(QtCore.QRect(20, 40, 91, 17))
        self.radioButton_leftHips.setObjectName("radioButton_leftHips")
        self.radioButton__rightLeftHips = QtWidgets.QRadioButton(self.DOA)
        self.radioButton__rightLeftHips.setGeometry(QtCore.QRect(20, 60, 171, 17))
        self.radioButton__rightLeftHips.setObjectName("radioButton__rightLeftHips")
        self.checkBox_Hips1 = QtWidgets.QCheckBox(self.DOA)
        self.checkBox_Hips1.setGeometry(QtCore.QRect(20, 100, 70, 17))
        self.checkBox_Hips1.setObjectName("checkBox_Hips1")
        self.checkBox_Hips2 = QtWidgets.QCheckBox(self.DOA)
        self.checkBox_Hips2.setGeometry(QtCore.QRect(20, 120, 70, 17))
        self.checkBox_Hips2.setObjectName("checkBox_Hips2")
        self.checkBox_Hips3 = QtWidgets.QCheckBox(self.DOA)
        self.checkBox_Hips3.setGeometry(QtCore.QRect(20, 140, 70, 17))
        self.checkBox_Hips3.setObjectName("checkBox_Hips3")
        self.checkBox_Hips4 = QtWidgets.QCheckBox(self.DOA)
        self.checkBox_Hips4.setGeometry(QtCore.QRect(20, 160, 70, 17))
        self.checkBox_Hips4.setObjectName("checkBox_Hips4")
        self.DOA_3 = QtWidgets.QGroupBox(self.joint_tab)
        self.DOA_3.setGeometry(QtCore.QRect(220, 10, 211, 221))
        self.DOA_3.setObjectName("DOA_3")
        self.pushButton_DOAKnees = QtWidgets.QPushButton(self.DOA_3)
        self.pushButton_DOAKnees.setGeometry(QtCore.QRect(0, 180, 211, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_DOAKnees.setFont(font)
        self.pushButton_DOAKnees.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_DOAKnees.setObjectName("pushButton_DOAKnees")
        self.radioButton_rightKnee = QtWidgets.QRadioButton(self.DOA_3)
        self.radioButton_rightKnee.setGeometry(QtCore.QRect(20, 20, 91, 17))
        self.radioButton_rightKnee.setObjectName("radioButton_rightKnee")
        self.radioButton_LeftKnee = QtWidgets.QRadioButton(self.DOA_3)
        self.radioButton_LeftKnee.setGeometry(QtCore.QRect(20, 40, 91, 17))
        self.radioButton_LeftKnee.setObjectName("radioButton_LeftKnee")
        self.radioButton_rightLeftKnees = QtWidgets.QRadioButton(self.DOA_3)
        self.radioButton_rightLeftKnees.setGeometry(QtCore.QRect(20, 60, 171, 17))
        self.radioButton_rightLeftKnees.setObjectName("radioButton_rightLeftKnees")
        self.checkBox_knees1 = QtWidgets.QCheckBox(self.DOA_3)
        self.checkBox_knees1.setGeometry(QtCore.QRect(20, 100, 70, 17))
        self.checkBox_knees1.setObjectName("checkBox_knees1")
        self.checkBox_knees2 = QtWidgets.QCheckBox(self.DOA_3)
        self.checkBox_knees2.setGeometry(QtCore.QRect(20, 120, 70, 17))
        self.checkBox_knees2.setObjectName("checkBox_knees2")
        self.checkBox_knees3 = QtWidgets.QCheckBox(self.DOA_3)
        self.checkBox_knees3.setGeometry(QtCore.QRect(20, 140, 70, 17))
        self.checkBox_knees3.setObjectName("checkBox_knees3")
        self.checkBox_knees4 = QtWidgets.QCheckBox(self.DOA_3)
        self.checkBox_knees4.setGeometry(QtCore.QRect(20, 160, 70, 17))
        self.checkBox_knees4.setObjectName("checkBox_knees4")
        self.pushButton_calcaneus_right = QtWidgets.QPushButton(self.joint_tab)
        self.pushButton_calcaneus_right.setGeometry(QtCore.QRect(450, 20, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_calcaneus_right.setFont(font)
        self.pushButton_calcaneus_right.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_calcaneus_right.setObjectName("pushButton_calcaneus_right")
        self.pushButton_calcaneus_left = QtWidgets.QPushButton(self.joint_tab)
        self.pushButton_calcaneus_left.setGeometry(QtCore.QRect(710, 20, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_calcaneus_left.setFont(font)
        self.pushButton_calcaneus_left.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_calcaneus_left.setObjectName("pushButton_calcaneus_left")
        self.main.addTab(self.joint_tab, "")
        self.mammography_tab = QtWidgets.QWidget()
        self.mammography_tab.setObjectName("mammography_tab")
        self.main.addTab(self.mammography_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButtonOBP = QtWidgets.QPushButton(self.tab)
        self.pushButtonOBP.setGeometry(QtCore.QRect(10, 10, 191, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 206, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButtonOBP.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButtonOBP.setFont(font)
        self.pushButtonOBP.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButtonOBP.setObjectName("pushButtonOBP")
        self.main.addTab(self.tab, "")
        self.OMC_number = QtWidgets.QLabel(self.centralwidget)
        self.OMC_number.setGeometry(QtCore.QRect(0, 0, 381, 49))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.OMC_number.setFont(font)
        self.OMC_number.setTextFormat(QtCore.Qt.RichText)
        self.OMC_number.setObjectName("OMC_number")
        self.pushButton_WritePass = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_WritePass.setGeometry(QtCore.QRect(650, 0, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_WritePass.setFont(font)
        self.pushButton_WritePass.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_WritePass.setObjectName("pushButton_WritePass")
        self.pushButton_getText = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_getText.setGeometry(QtCore.QRect(390, 0, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_getText.setFont(font)
        self.pushButton_getText.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_getText.setObjectName("pushButton_getText")
        self.pushButton_antiSleep = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_antiSleep.setGeometry(QtCore.QRect(800, 0, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_antiSleep.setFont(font)
        self.pushButton_antiSleep.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_antiSleep.setObjectName("pushButton_antiSleep")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(220, 100, 441, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 100, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_ok = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ok.setGeometry(QtCore.QRect(680, 100, 81, 31))
        self.pushButton_ok.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.pushButton_ok.setObjectName("pushButton_ok")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.start_IK_Butt = QtWidgets.QAction(MainWindow)
        self.start_IK_Butt.setObjectName("start_IK_Butt")
        self.restart_IK_butt = QtWidgets.QAction(MainWindow)
        self.restart_IK_butt.setObjectName("restart_IK_butt")
        self.end_IK = QtWidgets.QAction(MainWindow)
        self.end_IK.setObjectName("end_IK")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addSeparator()
        self.menu.addSeparator()
        self.menu.addAction(self.action)
        self.menu.addSeparator()
        self.menu.addAction(self.start_IK_Butt)
        self.menu.addSeparator()
        self.menu.addAction(self.restart_IK_butt)
        self.menu.addSeparator()
        self.menu.addAction(self.end_IK)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Мой асисстент"))
        self.family.setText(_translate("MainWindow", "Фамилия"))
        self.name.setText(_translate("MainWindow", "имя"))
        self.middle_name.setText(_translate("MainWindow", "Отчество"))
        self.birth_date.setText(_translate("MainWindow", "Дата рождения"))
        self.pushButton_fluraNorma.setText(_translate("MainWindow", "Флюорография норма"))
        self.pushButton_fluraNorma.clicked.connect(lambda: fluraNorma())
        self.pushButton_fluraNormaShort.setText(_translate("MainWindow", "Флюорография норма \"кор.\""))
        self.pushButton_fluraNormaShort.clicked.connect(lambda: fluraNormaShort())
        self.pushButton_TBCExodus.setText(_translate("MainWindow", "Исх. TBC в плотные очаги справа и сл."))
        self.pushButton_TBCExodusRight.setText(_translate("MainWindow", "Исход TBC в плотные очаги справа "))
        self.pushButton_TBCExodusRight_2.setText(_translate("MainWindow", "Исход TBC в плотные очаги слева"))
        self.OGKButton_OGKprint.setText(_translate("MainWindow", "ОГК норма(Печать)"))
        self.OGKButton_OGKprint.clicked.connect(lambda: rOGKPrint())
        self.OGKAutoButton.setText(_translate("MainWindow", "ОГК (Авто)"))
        self.OGKAutoButton.clicked.connect(lambda: autoOGKNorma())
        self.pushButton_fluraNormaAvto.setText(_translate("MainWindow", "Флюоро (авто)"))
        self.pushButton_fluraNormaAvto.clicked.connect(lambda: autoFluraNorma())
        self.OGKButtonCT.setText(_translate("MainWindow", "ОГК норма (СТ)"))
        self.OGKButtonCT.clicked.connect(lambda: OGKNormaCT())
        self.pushButton_fluraNormaCT.setText(_translate("MainWindow", "Флюорография норма(СТ)"))
        self.pushButton_fluraNormaCT.clicked.connect(lambda: fluraNormaCT())
        self.pushButton_pneumonia_right.setText(_translate("MainWindow", "Правосторонняя пневмония"))
        self.pushButton_pneumonia_left.setText(_translate("MainWindow", "Левосторонняя пневмония"))
        self.pushButton_pneumonia_right_left.setText(_translate("MainWindow", "Двусторонняя пневмония"))
        self.pushButton_OGK_norma.setText(_translate("MainWindow", "ОГК норма"))
        self.pushButton_OGK_norma.clicked.connect(lambda: rOGK())
        self.pushButton_plevrit_left.setText(_translate("MainWindow", "Левосторонний плеврит"))
        self.pushButton_plevrit_right.setText(_translate("MainWindow", "Правосторонний плеврит"))
        self.pushButton_fluraShortAuto.setText(_translate("MainWindow", "Флюоро короткая(авто)"))
        self.pushButton_fluraShortAuto.clicked.connect(lambda: autoFluraNormaRefferal())
        self.main.setTabText(self.main.indexOf(self.OGK_tab), _translate("MainWindow", "ОГК"))
        self.pushButton_shopOX.setText(_translate("MainWindow", "ШОП остеохондроз"))
        self.pushButton_shopOX.clicked.connect(lambda: shop())
        self.pushButton_gopOX.setText(_translate("MainWindow", "ГОП Остеохондроз"))
        self.pushButton_popOX.setText(_translate("MainWindow", "ПОП Остеохондроз"))
        self.pushButton_popOX.clicked.connect(lambda: pop())
        self.pushButton_shopGopOX.setText(_translate("MainWindow", "ШОП и ГОП Остеохондроз"))
        self.pushButton_shopGopOX.clicked.connect(lambda: shopGop())
        self.pushButton_GopPopOX.setText(_translate("MainWindow", "ГОП и ПОП Остеохондроз"))
        self.main.setTabText(self.main.indexOf(self.backbone_tab), _translate("MainWindow", "Позвоночник"))
        self.pushButton_craniumNorma.setText(_translate("MainWindow", "Череп норма"))
        self.pushButton_craniumNorma.clicked.connect(lambda: craniumNorma())
        self.pushButton_ppnNorma.setText(_translate("MainWindow", "ППН норма"))
        self.pushButton_ppnNorma.clicked.connect(lambda: ppnNorma())
        self.pushButton_ppnSinusitRight.setText(_translate("MainWindow", "синусит справа"))
        self.pushButton_ppnSinusitRight.clicked.connect(lambda: ppnSinusitRight())
        self.pushButton_ppnSinusitLeft.setText(_translate("MainWindow", "синусит слева"))
        self.pushButton_ppnSinusitLeft.clicked.connect(lambda: ppnSinusitLeft())
        self.pushButton_ppnSinusitRightLeft.setText(_translate("MainWindow", "синусит справа и слева"))
        self.main.setTabText(self.main.indexOf(self.cranium_ppn_tab), _translate("MainWindow", "Череп, Пазухи"))
        self.pushButton_cranium_lungs.setText(_translate("MainWindow", "Череп легкие"))
        self.pushButton_cranium_lungs.clicked.connect(lambda: craniumLungsMacros())
        self.pushButton_lungs_belly.setText(_translate("MainWindow", "легкие брюшная"))
        self.pushButton_lungs_belly.clicked.connect(lambda: OgkObpNorma())
        self.pushButton_ppnLungs.setText(_translate("MainWindow", "ППН легкие норма"))
        self.pushButton_pop_hips.setText(_translate("MainWindow", "ПОП Т/б сустав"))
        self.main.setTabText(self.main.indexOf(self.double_shablon_tab), _translate("MainWindow", "Двойные шаблоны"))
        self.pushButton_perelom_tip_left.setText(_translate("MainWindow", "перелом левой/л кости в типичном месте"))
        self.pushButton_perelom_tip_right.setText(_translate("MainWindow", "перелом правой/л кости в типичном месте"))
        self.pushButton_BonesNorma.setText(_translate("MainWindow", "без видимой костной патологии"))
        self.main.setTabText(self.main.indexOf(self.trauma_tab), _translate("MainWindow", "Травмы"))
        self.DOA.setTitle(_translate("MainWindow", "ДОА т/б сустава"))
        self.pushButton_DOAHips.setText(_translate("MainWindow", "ДОА Т/б сустава"))
        self.radioButton_rightHips.setText(_translate("MainWindow", "правого"))
        self.radioButton_leftHips.setText(_translate("MainWindow", "левого"))
        self.radioButton__rightLeftHips.setText(_translate("MainWindow", "правого и левого"))
        self.checkBox_Hips1.setText(_translate("MainWindow", "ст.1"))
        self.checkBox_Hips2.setText(_translate("MainWindow", "ст.2"))
        self.checkBox_Hips3.setText(_translate("MainWindow", "ст.3"))
        self.checkBox_Hips4.setText(_translate("MainWindow", "ст.4"))
        self.DOA_3.setTitle(_translate("MainWindow", "ДОА коленного сустава"))
        self.pushButton_DOAKnees.setText(_translate("MainWindow", "ДОА коленного сустава"))
        self.radioButton_rightKnee.setText(_translate("MainWindow", "правого"))
        self.radioButton_LeftKnee.setText(_translate("MainWindow", "левого"))
        self.radioButton_rightLeftKnees.setText(_translate("MainWindow", "правого и левого"))
        self.checkBox_knees1.setText(_translate("MainWindow", "ст.1"))
        self.checkBox_knees2.setText(_translate("MainWindow", "ст.2"))
        self.checkBox_knees3.setText(_translate("MainWindow", "ст.3"))
        self.checkBox_knees4.setText(_translate("MainWindow", "ст.4"))
        self.pushButton_calcaneus_right.setText(_translate("MainWindow", "пяточная шпора справа"))
        self.pushButton_calcaneus_left.setText(_translate("MainWindow", "пяточная шпора слева"))
        self.main.setTabText(self.main.indexOf(self.joint_tab), _translate("MainWindow", "Суставы, кости"))
        self.main.setTabText(self.main.indexOf(self.mammography_tab), _translate("MainWindow", "Маммография"))
        self.pushButtonOBP.setText(_translate("MainWindow", "Живот норма"))
        self.main.setTabText(self.main.indexOf(self.tab), _translate("MainWindow", "Живот"))
        self.OMC_number.setText(_translate("MainWindow", "Номер полиса"))
        self.pushButton_WritePass.setText(_translate("MainWindow", "ввести пароль"))
        self.pushButton_WritePass.clicked.connect(lambda: keyMacros())
        self.pushButton_getText.setText(_translate("MainWindow", "Получить данные пациента"))
        self.pushButton_getText.clicked.connect(lambda: getText())
        self.pushButton_antiSleep.setText(_translate("MainWindow", "key"))
        self.pushButton_antiSleep.clicked.connect(lambda: writeKey())
        self.label.setText(_translate("MainWindow", "Ручной ввод пациента"))
        self.pushButton_ok.setText(_translate("MainWindow", "ok"))
        self.pushButton_ok.clicked.connect(lambda: self.get_write_data())
        self.menu.setTitle(_translate("MainWindow", "инфоклиника"))
        self.start_IK_Butt.setText(_translate("MainWindow", "запустить инфоклинику"))
        self.start_IK_Butt.triggered.connect(lambda: self.click_start_ik())
        self.restart_IK_butt.setText(_translate("MainWindow", "перезапустить инфоклинику"))
        self.restart_IK_butt.triggered.connect(lambda: self.click_restart_ik())
        self.end_IK.setText(_translate("MainWindow", "закрыть инфоклинику"))
        self.end_IK.triggered.connect(lambda: self.click_end_ik())
        self.action.setText(_translate("MainWindow", "включить камеру"))

    def get_write_data(self):
        writeText(self.lineEdit.text())

    def click_start_ik(self):
        startIK()

    def click_restart_ik(self):
        restartIK()

    def click_end_ik(self):
        endIK()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
