import sys
import time
from collections import deque

from PyQt5 import QtWidgets, QtGui
from PyQt5.QtWidgets import QApplication, QMainWindow, QMenu, QDialog

from filter_text import writeText, writeOMC
from find_errors import FindErrors as FE
from get_text import getText
from keyboard import keyboardTap, keyboardLongTap, KeyboardPackagesUdp as KP
from find_button import FindButton as FB
from find_title import FindTitles as FT
from macros.backbone_macros import pop, shop
from macros.cranium_macros import craniumNorma
from macros.lungs_macros import rOGK, rOGKPrint, fluraNorma, fluraNormaShort
from macros.get_text_macros_from_otrt import getTextFromOTRT
from macros.macros import antiSleep, startIK, restartIK
from macros.ppn_macros import ppnNorma
import pyautogui as pag
from windows_control import WindowsControl as WC
from mouse import mouseTap, MousePackagesUdp as MP, mousePosition, initialMousePosition, mouseDoubleLKMTap

FIOList = deque([])
my_iter = iter(FIOList)


def autoFluraNorma():
    while True:
        try:
            FIO = next(my_iter)
            print(FIO)
            writeText(FIO)
            time.sleep(2)
            fluraNormaShort()
        except StopIteration:
            break


# FB.find(FB.playButton, debug_mode=True)
#autoFluraNorma()
# antiSleep()
#getTextFromOTRT()
# writeOMC()
#startIK()
# writeText('турченков андрей владимирович')
# time.sleep(2)
# writeText('1')
# fluraNorma()
#fluraNormaShort()
# rOGKPrint()
# kneesJoints()
# ppnNorma()
# pop()
# craniumNorma()
# shop()
# filter_text()
# FB.find(FB.infoclinicaButton, debug_mode=True)
getText()
time.sleep(3)
fluraNorma()
#rOGK()






# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    argument = None

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.DOAHipsLabel = QtWidgets.QGroupBox(Form)
        self.DOAHipsLabel.setGeometry(QtCore.QRect(10, 10, 211, 231))
        self.DOAHipsLabel.setObjectName("DOAHipsLabel")
        self.pushButton_DOAHips = QtWidgets.QPushButton(self.DOAHipsLabel, clicked=lambda: self.onClicked())
        self.pushButton_DOAHips.setGeometry(QtCore.QRect(0, 190, 211, 40))
        self.pushButton_DOAHips.setStyleSheet("background-color: rgb(206, 206, 206);\n""border-radius: 5px")
        self.pushButton_DOAHips.setObjectName("pushButton_DOAHips")
        self.groupBox = QtWidgets.QGroupBox(self.DOAHipsLabel)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 191, 61))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        hboxLayout = QtWidgets.QHBoxLayout()
        self.radioButton_rightLeftHips = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_rightLeftHips.setGeometry(QtCore.QRect(0, 0, 171, 17))
        self.radioButton_rightLeftHips.setObjectName("radioButton__rightLeftHips")
        self.radioButton_rightHips = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_rightHips.setGeometry(QtCore.QRect(0, 20, 91, 17))
        self.radioButton_rightHips.setObjectName("radioButton_rightHips")
        self.radioButton_leftHips = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_leftHips.setGeometry(QtCore.QRect(0, 40, 91, 17))
        self.radioButton_leftHips.setObjectName("radioButton_leftHips")
        self.groupBox_2 = QtWidgets.QGroupBox(self.DOAHipsLabel)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 100, 191, 81))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_st1 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_st1.setGeometry(QtCore.QRect(0, 0, 111, 17))
        self.radioButton_st1.setObjectName("radioButton_st1")
        self.radioButton_st2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_st2.setGeometry(QtCore.QRect(0, 20, 82, 17))
        self.radioButton_st2.setObjectName("radioButton_st2")
        self.radioButton_st3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_st3.setGeometry(QtCore.QRect(0, 40, 82, 17))
        self.radioButton_st3.setObjectName("radioButton_st3")
        self.radioButton_st4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_st4.setGeometry(QtCore.QRect(0, 60, 82, 17))
        self.radioButton_st4.setObjectName("radioButton_st4")
        self.radioButton_st3_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_st3_4.setGeometry(QtCore.QRect(90, 40, 82, 17))
        self.radioButton_st3_4.setObjectName("radioButton_st3_4")
        self.radioButton_st1_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_st1_2.setGeometry(QtCore.QRect(90, 0, 111, 17))
        self.radioButton_st1_2.setObjectName("radioButton_st1_2")
        self.radioButton_st2_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_st2_3.setGeometry(QtCore.QRect(90, 20, 82, 17))
        self.radioButton_st2_3.setObjectName("radioButton_st2_3")
        self.radioButton_ankiloz = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_ankiloz.setGeometry(QtCore.QRect(90, 60, 101, 17))
        self.radioButton_ankiloz.setObjectName("radioButton_ankiloz")

        self.groupBox.setLayout(hboxLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.DOAHipsLabel.setTitle(_translate("Form", "ДОА т/б сустава"))
        self.pushButton_DOAHips.setText(_translate("Form", "ДОА Т/б сустава"))
        self.radioButton_rightLeftHips.setText(_translate("Form", "правого и левого"))
        self.radioButton_rightHips.setText(_translate("Form", "правого"))
        self.radioButton_leftHips.setText(_translate("Form", "левого"))
        self.radioButton_st1.setText(_translate("Form", "ст.1"))
        self.radioButton_st2.setText(_translate("Form", "ст.2"))
        self.radioButton_st3.setText(_translate("Form", "ст.3"))
        self.radioButton_st4.setText(_translate("Form", "ст.4"))
        self.radioButton_st3_4.setText(_translate("Form", "ст.3-4"))
        self.radioButton_st1_2.setText(_translate("Form", "ст.1-2"))
        self.radioButton_st2_3.setText(_translate("Form", "ст.2-3"))
        self.radioButton_ankiloz.setText(_translate("Form", "Анкилоз?"))

    def onClicked(self):
        if self.radioButton_rightLeftHips.isChecked() == True:
            argument = 'правого и левого'
        elif self.radioButton_rightHips.isChecked():
            print('Right')
        elif self.radioButton_leftHips.isChecked():
            print('Left')

        if self.radioButton_st1.isChecked():
            print('1')
        elif self.radioButton_st2.isChecked():
            print('2')
        elif self.radioButton_st3.isChecked():
            print('3')
        elif self.radioButton_st4.isChecked():
            print('')
        elif self.radioButton_st1_2.isChecked():
            print('1-2')
        elif self.radioButton_st2_3.isChecked():
            print('2-3')
        elif self.radioButton_st3_4.isChecked():
            print('3-4')
        return self.argument


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
