# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainShort.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 800)
        font = QtGui.QFont()
        font.setPointSize(13)
        MainWindow.setFont(font)
        #главный текст
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.family_text = QtWidgets.QLabel(self.centralwidget)
        self.family_text.setGeometry(QtCore.QRect(10, 40, 260, 50))
        self.family_text.setTextFormat(QtCore.Qt.RichText)
        self.family_text.setObjectName("family_text")
        self.name_text = QtWidgets.QLabel(self.centralwidget)
        self.name_text.setGeometry(QtCore.QRect(240, 40, 260, 50))
        self.name_text.setTextFormat(QtCore.Qt.RichText)
        self.name_text.setObjectName("name_text")
        self.middle_name_text = QtWidgets.QLabel(self.centralwidget)
        self.middle_name_text.setGeometry(QtCore.QRect(510, 40, 260, 50))
        self.middle_name_text.setTextFormat(QtCore.Qt.RichText)
        self.middle_name_text.setObjectName("middle_name_text")
        self.birth_date_text = QtWidgets.QLabel(self.centralwidget)
        self.birth_date_text.setGeometry(QtCore.QRect(800, 40, 260, 50))
        self.birth_date_text.setTextFormat(QtCore.Qt.RichText)
        self.birth_date_text.setObjectName("birth_date_text")
        self.OMC_text = QtWidgets.QLabel(self.centralwidget)
        self.OMC_text.setGeometry(QtCore.QRect(10, 0, 307, 49))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.OMC_text.setFont(font)
        self.OMC_text.setTextFormat(QtCore.Qt.RichText)
        self.OMC_text.setObjectName("OMC_text")

        #Меню бар

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.start_IK_Butt = QtWidgets.QAction(MainWindow)
        self.start_IK_Butt.setObjectName("start_IK_Butt")
        self.start_IK_Butt.triggered.connect(lambda: startIK())
        self.restart_IK_butt = QtWidgets.QAction(MainWindow)
        self.restart_IK_butt.setObjectName("restart_IK_butt")
        self.restart_IK_butt.triggered.connect(lambda: restartIK())
        self.menu.addAction(self.start_IK_Butt)
        self.menu.addAction(self.restart_IK_butt)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)





    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Мой асисстент"))
        self.family_text.setText(_translate("MainWindow", "Фамилия"))
        self.family_text.setText(last_name_data)
        self.family_text.adjustSize()
        self.name_text.setText(_translate("MainWindow", "имя"))
        self.name_text.setText(first_name_data)
        self.name_text.adjustSize()
        self.middle_name_text.setText(_translate("MainWindow", "Отчество"))
        self.middle_name_text.setText(middle_name_data)
        self.middle_name_text.adjustSize()
        self.birth_date_text.setText(_translate("MainWindow", "Дата рождения"))
        self.birth_date_text.setText(birth_date_data)
        self.birth_date_text.adjustSize()
        self.OMC_text.setText(_translate("MainWindow", "Номер полиса"))
        self.OMC_text.setText(OMCdata)
        self.OMC_text.adjustSize()
        self.menu.setTitle(_translate("MainWindow", "инфоклиника"))
        self.start_IK_Butt.setText(_translate("MainWindow", "запустить инфоклинику"))
        self.restart_IK_butt.setText(_translate("MainWindow", "перезапустить инфоклинику"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())